name: RSS → Discord

# Ce workflow se déclenche toutes les 5 minutes, et peut aussi être lancé manuellement
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupère ton code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2) Installe Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Installe les dépendances nécessaires
      - name: Install dependencies
        run: pip install feedparser openai requests

      # 4) Lance ton script notifier.py
      - name: Run notifier
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          OPENAI_API_KEY:      ${{ secrets.OPENAI_API_KEY }}
        run: python notifier.py
